### PR TITLE
Fix bugs pertaining to view and dress code

### LINKED ISSUE #126: [PE-D] Definition of valid outfit for view command does not match intended product usage
At present, a valid outfit in the `view` command specifies only that the outfit must have `upper`, `lower`, and `footwear`. However, there is no restriction in the dress code (for example, that the dress code must match). This does not appear to match the intended product usage of viewing a valid outfit.

However, if this is intended behaviour, it must be justified and specified in the user guide.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: kingsleykuan/ped#6

### PR DESCRIPTION
**Pull request by adidoesnt**

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/ViewCommand.java [hunk 1]
```diff
@@ -62,7 +63,11 @@ public CommandResult execute(Model model) throws CommandException {
             }
             viewList.add(garmentToView);
         }
-
+        for (Garment g : viewList) {
+            if (!g.getDressCode().equals(viewList.get(0).getDressCode())) {
+                throw new CommandException(MESSAGE_DIFFERENT_DRESSCODE);
+            }
+        }
         Predicate<Garment> predicateViewGarments = garment -> viewList.contains(garment);
```
Comment (Jonathan-Cao) [inline src/main/java/seedu/address/logic/commands/ViewCommand.java:71]: Great job!

**Review by Jonathan-Cao — APPROVED** [review]
LGTM.
