### PR TITLE
Fix Find Command Parser to reject redundant search query parameters

### LINKED ISSUE #128: [PE-D] Find command accepts arbitary inputs as attributes
The `find` command accepts any arbitrary input as attributes. For example, `s/test`, `r/test`, and `t/test`, which contradicts the user guide.

Example input:
`find r/test`

User Guide:

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: kingsleykuan/ped#8

### PR DESCRIPTION
**Pull request by adidoesnt**
Parameters refer to size, dressCode, and type.

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/FindCommand.java [hunk 1]
```diff
@@ -23,8 +23,10 @@
     public static final String MESSAGE_USAGE = COMMAND_WORD + ": Finds all garments whose names, colours, sizes, "
             + "dresscodes or descriptions contain any of the specified\n"
             + "keywords (case-insensitive) and displays them as a list with index numbers.\n"
-            + "Parameters: n/KEYWORD [MORE_KEYWORDS] or s/KEYWORD [MORE_KEYWORDS] ... for each attribute\n"
-            + "Example: " + COMMAND_WORD + " n/worn out jeans";
+            + "Parameters: n/KEYWORD [MORE_KEYWORDS] or s/KEYWORD [MORE_KEYWORDS] ... for each attribute.\n"
+            + "Example: " + COMMAND_WORD + " n/alice bob charlie\n"
+            + "For dress code, [KEYWORD] must be either casual, formal, or active\n"
+            + "For type, [KEYWORD] must be upper, lower, or footwear.";
```
Comment (Jonathan-Cao) [inline src/main/java/seedu/address/logic/commands/FindCommand.java:30]: Good clarification!

**Review by Jonathan-Cao — APPROVED** [review]
LGTM.
